version: '2'
services:
  web:
    build:
      context: .
      dockerfile: ./src/client/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./:/usr/src/app:rw"
    environment:
      - NODE_ENV=dev
    command: >
      sh -c '
      if test -d node_modules;
      then
        echo node_modules_exists ;
      else
        cp -a /tmp/node_modules /usr/src/app/node_modules;
      fi &&
      npm install && npm start
      '
  api:
    build:
      context: .
      dockerfile: ./src/server/Dockerfile
    depends_on:
      - web
    ports:
      - "3000:3000"
    volumes:
      - "./:/usr/src/app:rw"
    environment:
      - NODE_ENV=dev
    command: >
      sh -c '
      if test -d node_modules;
      then
        echo node_modules_exists ;
      else
        cp -a /tmp/node_modules /usr/src/app/node_modules;
      fi &&
      npm install && npm run server
      '
