version: '2'
services:
  db: 
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - "/tmp/hrdb:/data/db"
  mongoclient:
    image: mongoclient/mongoclient
    ports:
      - "3001:3000"
  hapi:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - "/usr/src/app/node_modules"