version: '2'
services:
  db: 
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - "/Users/daynedavis/db:/db"
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.devServer
    ports:
      - "8080:8080"
    volumes:
      - "./:/usr/src/app:rw"
    environment:
      - NODE_ENV=dev
  hapi:
    build:
      context: .
      dockerfile: ./Dockerfile.server
    ports:
      - "3000:3000"
    volumes:
      - "./:/usr/src/app:rw"
    environment:
      - NODE_ENV=dev